version: '3'
services:
  nginx:
   container_name: m-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
   - /var/www/arepoforyourproject:/usr/share/nginx/html
   - ./nginx/conf.d/my:/etc/nginx/conf.d
    
  mysql:
   container_name: m-mysql
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   volumes:
   - /usr/local/data:/var/lib/mysql
   - ./mysql:/etc/mysql/conf.d
   restart: always
    
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone:ro
      - ./app:/app
      - /var/www/log:/src
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=prod